name: Publish compiled jar to GitHub releases

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin

      - name: Build jar
        run: mvn package

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: MatchBot-1.0.0-SNAPSHOT.jar
          path: target/MatchBot-1.0.0-SNAPSHOT.jar

      - name: Move generated jar file
        run: mv target/MatchBot-1.0.0-SNAPSHOT.jar MatchBot-1.0.0-SNAPSHOT.jar

      - name: Create Release
        id: create_release
        if: github.event_name != 'pull_request' && github.ref == 'refs/heads/main'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: MatchBot-${{ github.sha }}
          release_name: Release MatchBot-${{ github.sha }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        if: github.event_name != 'pull_request' && github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./MatchBot-1.0.0-SNAPSHOT.jar
          asset_name: MatchBot-1.0.0-SNAPSHOT.jar
          asset_content_type: application/java-archive
          tag: MatchBot-${{ github.sha }}